### ISSUE TITLE
Proposal to remove the Time property from a POS transaction - PoSv4

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore#10]
### This issue will track the discussion around this proposal 

As part of the work on ObsidianX (ODX) @aubergemediale has proposed that we remove the Time property form a POS transaction as this is not really needed, a coinstake is attached to a block and the block time must be the same to a coinstake trx.

Time field is a left over of coinage that was intended to have some weight in the UTXO ability to participate in staking but that was ditched in previous algo versions
See the white paper for more info
https://decred.org/research/king2012.pdf
https://blackcoin.org/blackcoin-pos-protocol-v2-whitepaper.pdf

**Impact on existing chains** - they should mandate a time span padding of zeros to avoid malleability and potentially increment protocol version to know what type of trx to send to peers.

**Comment by aubergemediale** [comment]
A working implementation of this, which I call PoS v4 is here:
https://github.com/obsidianproject/Obsidian-StratisNode/pull/40
The changes should not break existing code but enable the new method (without tx.Time) by simply supplying a Transaction instead of a PosTransaction from the factory.

**Comment by dangershony** [comment]
This is done and currently live on ODX testnet
