### ISSUE TITLE
Enable pruning on the full node

### ISSUE THREAD

**Issue by thecrypt0hunter** [block-core/blockcore#100]
It would be useful for nodes running on servers with constrained hard disk space to enable pruning.

**Comment by dangershony** [comment]
yeah, there is code for pruning but it was not good and based on dbreeze so the code needs to be revisited and needs a bit refactoring

**Comment by dangershony** [comment]
this is done here
https://github.com/block-core/blockcore/commit/5012a0a81ba792744461efc6ca15645462ae0638
