### ISSUE TITLE
Show the balance on the wallet/account when sending

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore#110]
Should perhaps show the account balance when on sending screen to see how much one can possibly send?

![image](https://user-images.githubusercontent.com/309938/81087646-47746500-8efa-11ea-81c7-f4d41356eb5a.png)

**Comment by dangershony** [comment]
Yes and add to that also to pre calculate the fee once the amount and address are selected, stratis core does that (and there is already a method called EstimateFee)
