### ISSUE TITLE
UI: Create favicon.ico handler 

### ISSUE THREAD

**Issue by thecrypt0hunter** [block-core/blockcore#132]
So it can change based on chain

**Comment by thecrypt0hunter** [comment]
https://github.com/block-core/blockcore-explorer-legacy/blob/master/src/Blockcore.Explorer/Handlers/FavoriteIconHandler.cs

**Comment by thecrypt0hunter** [comment]
then in "public void Configure(IApplicationBuilder app, IWebHostEnvironment env)" you do:

app.Map("/favicon", config => config.UseMiddleware<FavoriteIconHandler>());

**Comment by dangershony** [comment]
I think this was done @turcol ?
