### ISSUE TITLE
Need to add max network fee to the StandardTransactionPolicy

### ISSUE THREAD

**Issue by DennisAMenace** [block-core/blockcore#138]
This will be a consensus item change for all networks.

![image](https://user-images.githubusercontent.com/41244965/83178093-4e4b5d80-a0dd-11ea-8b03-6855150348d2.png)

**Comment by dangershony** [comment]
This was done right?

**Comment by DennisAMenace** [comment]
Once PR https://github.com/block-core/blockcore/pull/140 is committed, this will be complete.
