### ISSUE TITLE
Expand the wallet sync to sync only specific accounts.

### ISSUE THREAD

**Issue by DennisAMenace** [block-core/blockcore#153]
Currently, the API `/api/Wallet/sync` will resyncs from a block specified by its block hash.

Would be nice if we can expand this or modify the existing API to resync only an account within the wallet by the account name.

![image](https://user-images.githubusercontent.com/41244965/84093083-77f66580-a9b6-11ea-90c5-7c6f09845a47.png)

**Comment by dangershony** [comment]
What is the benefit to sync only a single account?

**Comment by DennisAMenace** [comment]
Creating a new API call, or extending this one I think will be useful if a project creates new custom accounts.

If the project has "feature x" that uses a new wallet account other than what we have by default, would it be beneficial to scan for transactions because the restore does not have any recollection of that custom account name.

**Comment by DennisAMenace** [comment]
Yeah, and the features would probably be well defined. I was thinking more for example an extension of the address book, where people could have accounts named different things.

This could be bad, because if they forgot what the name of that account was, it wouldn't be restored, and funds wouldn't appear during a restore if the address book data was not present.

Thanks for the discussion.
