### ISSUE TITLE
UI: Make the left sidebar max-width

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore#154]
The sidebar doesn't need to go beyond a certain size, and when it does, the header doesn't follow:

![image](https://user-images.githubusercontent.com/309938/84552285-7e674300-ad10-11ea-933a-e936bdb36160.png)

**Comment by thecrypt0hunter** [comment]
@sondreb can you check if this is fixed for you?

**Comment by sondreb** [comment]
Not fixed yet, maybe part of it but the width of the whole containing div shouldn't expand.

![image](https://user-images.githubusercontent.com/309938/84593577-2c780780-ae4d-11ea-9101-69ded1466ff1.png)

**Comment by thecrypt0hunter** [comment]
@sondreb it looks better now ... my monitor is small, I found a way to represent a larger monitor

**Comment by thecrypt0hunter** [comment]
@sondreb should be closed now

**Comment by thecrypt0hunter** [comment]
This is fixed
