### ISSUE TITLE
UI: Enabling staking should probably show different UI during activation

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore#156]
Right now it says:

"Node staking with 0.00000000 (0,00 % of the network weight 0.00000000), est. time to find new block is 00:00:00."

Right after activation, this should show an message that "Waiting activation" or something.

**Comment by thecrypt0hunter** [comment]
In this PR https://github.com/block-core/blockcore/pull/157 
I've added a wait while the activation occurs, but the stats take a little while to populate. Have a look and see what you think

**Comment by thecrypt0hunter** [comment]
Closing this
