### ISSUE TITLE
UI Feature: A link to the Swagger API Docs

### ISSUE THREAD

**Issue by MudDev** [block-core/blockcore#162]
On the dashboard, a nice way to access the API -> http://localhost:{CoinPort}/docs/index.html

I saw this on the older dashboard, it was removed, can we get it added again?

**Comment by thecrypt0hunter** [comment]
I’ll be adding it back .. just need to work out the UI

**Comment by thecrypt0hunter** [comment]
This is added on the new About page - thanks for the suggestion @MudDev
