### ISSUE TITLE
UI: Make sure that money rendering is same on "Staking" and "Wallets" pages

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore#180]
The "Staking" and "Wallets" pages shows money in different formats:

![image](https://user-images.githubusercontent.com/309938/86836263-87dc9480-c09d-11ea-879e-b4a4b1954da8.png)

![image](https://user-images.githubusercontent.com/309938/86836293-93c85680-c09d-11ea-894e-c28157fa2936.png)

**Comment by thecrypt0hunter** [comment]
This is fixed and can be closed
