### ISSUE TITLE
Nodes that are rejected inbound during IBD while not in IBD stage

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore#199]
See image bellow IBD is false but nodes are still rejected.

![image](https://user-images.githubusercontent.com/7487930/89029705-e73d6580-d326-11ea-90a9-f228a400acbc.png)

**Comment by dangershony** [comment]
As part of this change we should add an api endpoint to whitelist nodes

**Comment by soma42** [comment]
Did you see that the tip age is too old? Maybe close issue till we have a more current example, I am not aware of a problem here atm.

**Comment by dangershony** [comment]
Agree
