### ISSUE TITLE
Would be nice if public: ConsensusManager.IsConsensusConsideredToBeSyncedLocked / IChainedHeaderTree.GetBestPeerTip

### ISSUE THREAD

**Issue by soma42** [block-core/blockcore#202]
For some operations, it's good to know if the node is really synced, e.g. before sending a transaction, so that you don't include utxos that are already spent. ConsensusManager has this, but it's unfortunately private:

private bool IsConsensusConsideredToBeSyncedLocked(out ChainedHeader bestTip)

That's really very useful, even more so since it gives you the best peer tip! The method is related with the ConsensusIsConsideredToBeSyncedMargin constant. But you can use bestTip to set a wider or lower margin for your purpose or just access the value because you are curious.

Alternatively, ChainedHeader IChainedHeaderTree.GetBestPeerTip(); could be public.

**Comment by dangershony** [comment]
There are alternatives is ChainState

**Comment by soma42** [comment]
Ok good to know! I closed the issue because I had opened it, and I don't need this atm.
