### ISSUE TITLE
Make test runs deterministic

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore#206]
The current suite of tests is not deterministic and fails on initial runs. All test become green after re-running failed tests.

Appears to be some shared state or data that makes tests fail.

This would be a great benefit to fix, as pull requests and other CI builds would improve their usage as gate-keepers.

**Comment by dangershony** [comment]
The main problems are some integration tests that almost always fail on first run we need to check if they fail due to other tests running in the same test run first then open logs to get more clues on why they fail.

**Comment by sondreb** [comment]
#240 Closes this issue.
