### ISSUE TITLE
RemoveTransaction wallet tests fail in Blockcore.Features.Wallet.Tests

### ISSUE THREAD

**Issue by xandronus** [block-core/blockcore#210]
These two are failing for me:
```
RemoveTransactionsByIdsAlsoRemovesUnconfirmedSpendingDetailsTransactions
RemoveTransactionsByIdsWhenTransactionsAreUnconfirmedReturnsRemovedTransactionsList
```

Did a bit of investigation into this and these tests seems to use LiteDB which I don't think we are supporting? Seems related to the transaction ```CreationTime``` which the test seems to let default and not specify explicitly. I think I can fix it by setting a ```CreationTime``` but not sure whether these tests are useful since we aren't using LiteDB? Let me know if you think they are worth fixing and I'll fix them up.

**Comment by xandronus** [comment]
I have fixed these tests, but there is some strangeness around LiteDB and DateTime rounding. I'm not sure if anyone is using the LiteDb wallet implementation but if they are be aware there are some oddities around LiteDB - see this old issue https://github.com/mbdavid/LiteDB/issues/604

I also fixed some other wallet tests that made assumptions about date locality which don't pass for me.

**Comment by dangershony** [comment]
the tests are fine here I wonder what is different for you.

**Comment by xandronus** [comment]
They never pass for me - just pulled the current master and this is what I consistently get without my PR fix:
![image](https://user-images.githubusercontent.com/47086417/93498622-42271e00-f8cf-11ea-976f-39128d06ec37.png)

The remove transaction ones have errors like this:
``` 
RemoveTransactionsByIdsAlsoRemovesUnconfirmedSpendingDetailsTransactions
   Source: WalletManagerTest.cs line 3141
   Duration: 1.7 sec

  Message: 
    Assert.Contains() Failure
    Not found: (35810eb758fb0d937aff4fbfc24a17639a7e7763861b5372b79b5b76ed0c0d00, 1/1/0001 12:00:00 AM +00:00)
    In value:  HashSet<ValueTuple<uint256, DateTimeOffset>> [(35810eb758fb0d937aff4fbfc24a17639a7e7763861b5372b79b5b76ed0c0d00, 1/1/0001 7:00:00 AM +00:00)]
  Stack Trace: 
    WalletManagerTest.RemoveTransactionsByIdsAlsoRemovesUnconfirmedSpendingDetailsTransactions() line 3194
```

The wallet store ones are due to a localisation issue with the date parsing (I'm using US English):
```
WalletStore_GetAccountHistory
   Source: WalletStoreTest.cs line 228
   Duration: 131 ms

  Message: 
    System.FormatException : String '14/06/2020 01:28:21 +01:00' was not recognized as a valid DateTime.
  Stack Trace: 
    DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
    DateTimeOffset.Parse(String input)
    WalletStoreTest.Create(OutPoint outPoint, String address, Int32 accountIndex) line 294
    WalletStoreTest.WalletStore_GetAccountHistory() line 243
```
