### ISSUE TITLE
Compiling Rocksdb

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore#231]
This is to track info about making our own nuget of rocksdb that will have a compression library linked.

rocksdb src https://github.com/facebook/rocksdb

**The problem**
Using rocks will require to install a compression dependency (either snappy or another) in order to run on linux and Mac.
To avoid that we can compile a version without compression but this link indicate its a good idea to use [compression](https://github.com/warrenfalk/rocksdb-sharp/blob/ec649672cd6fc360eff7967371defdd8c2432b39/RocksDbSharp/ColumnFamilyOptions.cs#L1072) though for the size we use it may not be significant.
The problem is for linux and mac we need to install snappy [requirements](https://github.com/warrenfalk/rocksdb-sharp#requirements)

**Useful links**
Rocksdb sharp  https://github.com/warrenfalk/rocksdb-sharp
nuget https://www.nuget.org/packages/RocksDbSharp/
nuget native https://www.nuget.org/packages/RocksDbNative/

without snappy compression:
nuget https://www.nuget.org/packages/RockDb.Native/ 
src https://github.com/Skird/rocksdb 
diff form master (building the rocks dll using make-shared that I think will not need snappy dependency)
https://github.com/facebook/rocksdb/compare/master...Skird:master

issue on how snappy is used
https://github.com/facebook/rocksdb/issues/3308

installation instructions 
https://github.com/facebook/rocksdb/blob/master/INSTALL.md

about compression
https://github.com/facebook/rocksdb/wiki/Compression

I think the best approach is to take the `RockDb.Native` fork (which is behind master) and compile rocks dlls per env and publish a new nuget under blockcore.rocksdb.native that we can control its update

**Comment by checho1989** [comment]
From Discord discussion:
Apparently, the https://github.com/warrenfalk/rocksdb-sharp library is not maintained anymore, so use it for production will be hard to track issues.
@sondreb found some forks with active commits where we can move to have the latest version support for rocksdb.  

- https://github.com/NethermindEth/rocksdb-sharp

The basic problem with rocksdb-sharp in Linux and macOS has to install dependencies to run rocksdb, (snappy, lz4, lzsd), it's not functional for distribution packages and environments other than development.

Looking around I found some warrenfalk forks, they put the dependencies into the runtimes, in this case, we can build a full nugget package with dependencies support.

- https://github.com/curiosity-ai/rocksdb-sharp
- https://github.com/planetarium/rocksdb-sharp

**Comment by sondreb** [comment]
We now have our own build setup of RocksDB:

NuGet package:
https://github.com/block-core/blockcore-rocksdb

Native libraries:
https://github.com/block-core/blockcore-rocksdb-native

Our library works out of the box on Windows and Mac without any extra dependencies needed to be installed (libraries are included).

**Comment by dangershony** [comment]
THIS IS AWESOME
