### ISSUE TITLE
Sqlite wallet issue

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore#299]
Change to RELEASE mode, run any node, create a wallet and query for address.

This will fail

**Comment by sondreb** [comment]
![image](https://user-images.githubusercontent.com/309938/110490416-95e12a00-80f0-11eb-9023-58807c47f227.png)

**Comment by sondreb** [comment]
The issue is many requests at the same time. If you request the balance in the browser and keep refreshing, it will quickly begin crashing.

Example: http://localhost:33333/api/wallet/balance?walletName=main&accountName=account%200

**Comment by sondreb** [comment]
Eventually when reloading, you'll get the error out like this:
![image](https://user-images.githubusercontent.com/309938/110494013-75669f00-80f3-11eb-803b-4eafd6ab3a28.png)

**Comment by MithrilMan** [comment]
is it based on Dapper?
ensure the context is scoped, not a singleton, because if it's like EF, you can't run concurrent operation on the same context

**Comment by MithrilMan** [comment]
I checked fast, it seems dapper is used in WalletStore that is created once for each wallet, this mean it's a shared instance and since WalletStore create teh db connection in its constructor, that's the problem

in EF the dbcontext should be short living (like a unit of work), I suppose the same should be done on Dapper?

**Comment by dangershony** [comment]
I think dapper opens and closes the connection internally, I am not sure it needs to be short lived, but that's a place to look yes.

**Comment by dangershony** [comment]
But I am pretty sure the wallet has locks on it before even reaching the wallet store
