### ISSUE TITLE
How to get all bitcoin addresses with non zero balance

### ISSUE THREAD

**Issue by Stonica** [block-core/blockcore#327]
1- I appreciate if someone help me how to get all bitcoin addresses with non zero balance within blockcore or any other NBitcoin based solution?
2- Also I have my own Bitcoin Core FullNode which is completely synced and I don't want the Blockcore download the blockchain again, how to do it?

**Comment by sondreb** [comment]
1:
This is how you get unused addresses from your wallet:

http://localhost:4335/api/Wallet/unusedaddresses?WalletName=main1&AccountName=account%200&Count=10&Segwit=true

Replace the port with your own port.

The "WalletName" is the name of your wallet file, and the "AccountName" is "account 0", which is a value your normally don't control manually but you must supply in the API.

Last parameters is Count, which is number of address you want back, and Segwit, which will change the address types.

![image](https://user-images.githubusercontent.com/309938/114549536-6a0e1280-9c61-11eb-8b6b-7a14d0e5e922.png)

More API methods can be discovered here: http://localhost:4335/docs/index.html

2:
If you use the default data folder without specifying the -datadir argument, you will find the blockchain data on this path on Windows. As mentioned, you can use -datadir to specify a custom full path or relative path to a copy of your blockchain data folder.

`C:\Users\USERNAME\AppData\Roaming\Blockcore\bitcoin\Main`

**Comment by Stonica** [comment]
> 
> 
> 1:
> This is how you get unused addresses from your wallet:
> 
> http://localhost:4335/api/Wallet/unusedaddresses?WalletName=main1&AccountName=account%200&Count=10&Segwit=true
> 
> Replace the port with your own port.
> 
> The "WalletName" is the name of your wallet file, and the "AccountName" is "account 0", which is a value your normally don't control manually but you must supply in the API.
> 
> Last parameters is Count, which is number of address you want back, and Segwit, which will change the address types.
> 
> ![image](https://user-images.githubusercontent.com/309938/114549536-6a0e1280-9c61-11eb-8b6b-7a14d0e5e922.png)
> 
> More API methods can be discovered here: http://localhost:4335/docs/index.html
> 
> 2:
> If you use the default data folder without specifying the -datadir argument, you will find the blockchain data on this path on Windows. As mentioned, you can use -datadir to specify a custom full path or relative path to a copy of your blockchain data folder.
> 
> `C:\Users\USERNAME\AppData\Roaming\Blockcore\bitcoin\Main`

Thanks, 
1- Does it return all bitcoin addresses with positive balance of my wallet ?(if yes then I need all addresses regardless it is my own or for others, I think there are more than 30 million address with positive balance, I need all of them.

2- What I found from the docker container of blockcore fullnode, gave me the idea that datadir of blockcore's fullnode has different folder structure and files than Bitcoin Core's datadir, am I right?

**Comment by sondreb** [comment]
The data folder of Bitcoin Core is different then one made by Blockcore, different technologies and different storage.

You can run your node with "-addressindex=1" and you will build up an index of all the addresses on the blockchain, then there is REST API you can query. We will be refactoring how this is stored soon, as it relies on LiteDB which we are in the progress of migrating away from.

The other alternative is to run the Blockcore Indexer, which can be used for Explorer, etc.
