### ISSUE TITLE
[Bug] [Non-Technical] [Docs] The Discord invite on the Github docs is broken, must go to Blockcore website to access the invite

### ISSUE THREAD

**Issue by jeffward01** [block-core/blockcore#352]
The Discord invite on the Github docs is broken, must go to Blockcore website to access the invite

https://github.com/block-core/blockcore#:~:text=Join%20our%20community%20on%20discord.

**Comment by dangershony** [comment]
Ah thanks we'll fix it

**Comment by sondreb** [comment]
We have updated all links to Discord with a permalink: https://www.blockcore.net/discord

Thanks for reporting!
